### ISSUE TITLE
Where I can find the exercises in the course slides?

### ISSUE THREAD

**Issue by Ziaeemehr** [jlizier/jidt#82] opened 2020-09-26 08:11 UTC
Hi, I am following the videos for the course and they are really great, thank you for that.
There are some practice in the slides, that refer to some matlab code. Are they still available to play around?

Thank you in advance for any guide.

**Comment by jlizier** [comment] 2020-09-28 04:38
Hi Ziaeemehr,

Thanks - glad to hear that you like them!
At this stage only the videos and slides have been uploaded. The activities and associated code will be distributed at a later stage (hopefully soon when I have time).

Closing as this is not a bug.

--joe

**Closed by jlizier** 2020-09-28 04:38 UTC
