### ISSUE TITLE
Help to understand the code

### ISSUE THREAD

**Issue by socherbyc** [jlizier/jidt#72] opened 2018-11-18 18:00 UTC
Hi.

I'm trying to use Entropy Transfer for a project, but I'm not from statistics and I'm in trouble to understand some things.

For this code:

```py
from jpype import *
import random
import numpy
import math

# Change location of jar to match yours:
jarLocation = "infodynamics-jar-1.4/infodynamics.jar"
# Start the JVM (add the "-Xmx" option with say 1024M if you get crashes due to not enough memory space)
startJVM(getDefaultJVMPath(), "-ea", "-Djava.class.path=" + jarLocation)

def transfer_entropy(arrA, arrB):
    # Create a TE calculator and run it:
    teCalcClass = JPackage("infodynamics.measures.continuous.kernel").TransferEntropyCalculatorKernel
    teCalc = teCalcClass()
    teCalc.setProperty("NORMALISE", "true") # Normalise the individual variables
    teCalc.initialise(1, 0.5) # Use history length 1 (Schreiber k=1), kernel width of 0.5 normalised units
    teCalc.setObservations(JArray(JDouble, 1)(arrA), JArray(JDouble, 1)(arrB))
    result = teCalc.computeAverageLocalOfObservations()
    return result

def print_transfer_entropy(arrA, arrB):
    print("arrA -> arrB", transfer_entropy(arrA, arrB))
    print("arrB -> arrA", transfer_entropy(arrB, arrA))

print("\n Test 1") # ??
print_transfer_entropy(
    [-239,459,133,-195,257,-190,436,-247,35,120],
    [-239,459,133,-195,257,-190,436,-247,35,120]
)
print("\n Test 2") # OK
print_transfer_entropy(
    [459,133,-195,257,-190,436,-247,35,120,-407],
    [-407,459,133,-195,257,-190,436,-247,35,120]
)
print("\n Test 3") # ??
print_transfer_entropy(
    [1,2,1,2,1,2,1,2,1,2],
    [2,1,2,1,2,1,2,1,2,1]
)
print("\n Test 4") # ??
print_transfer_entropy(
    [1,2,3,4,5,6,7,8,9,10],
    [10,1,2,3,4,5,6,7,8,9]
)
print("\n Test 5") # ??
print_transfer_entropy(
    [random.randint(0,9) for x in range(10)],
    [random.randint(0,9) for x in range(10)]
)
```

I got these results:
```
 Test 1
arrA -> arrB 0.0
arrB -> arrA 0.0

 Test 2
arrA -> arrB 0.926650000320514
arrB -> arrA 0.9916458337339757

 Test 3
arrA -> arrB 0.0
arrB -> arrA 0.0

 Test 4
arrA -> arrB 0.0
arrB -> arrA 0.0

 Test 5
arrA -> arrB 0.46787742027762425
arrB -> arrA 0.46332500016025696
```

The expected result for the tests 3 and 4 wouldn't be "1"? (or something like the test 2?)

The expected result for the test 1 wouldn't be greater than "0"?

The expected result for the test 5 wouldn't be negative? And why, in this test, the result varies so much? (sometimes is 0.30, sometimes is 1.04, sometimes is 0.50 ...)

Thank for the patience and for this library.

**Comment by jlizier** [comment] 2018-11-19 10:23
Hi @socherbyc - I am closing this issue as it is not a bug report concerning JIDT. You should only open an Issue on repositories like github to report actual problems with the software, not because of a lack of understanding about the outputs. The appropriate channel for questions like these are over email.

I'll answer your questions briefly here anyway before closing.
Overall -- you need to have a much deeper read of transfer entropy literature - your queries are fairly simple ones about the nature of the measure itself (they don't pertain to the JIDT implementations). For this, I suggest you consult our transfer entropy book -- https://www.springer.com/gp/book/9783319432212 -- or you can go through the slides that are attached to the JIDT repository now -- see https://github.com/jlizier/jidt/tree/master/course and in particular go to [Module 9 slides](https://github.com/jlizier/jidt/blob/master/course/Module9-InformationTransfer/Lec9-InfoTransfer.pdf).

Test 3 and 4 are 0 because the next values of the target are predictable from the target past. Completely predictable for Test 3, and predictable within 0.5 standard deviations for Test 4 (that's what the kernel estimator as you'd set it up is doing). The source adds nothing beyond this.

In test 2, I think that you have multiple target values within 0.5 standard deviations of each other (eg -239, -247), so some ambiguity in the next value is left given that target past, and the source value can help to reduce that ambiguity. That is where the non-zero result comes from (in contrast to Test 4). The bigger issue for Test 2 is that you're undersampling by using only 10 samples so this result is rather spurious anyway. 

Test 1 - the source is the target past, so by definition cannot add anything beyond what we already have from the target past. Therefore the zero result.

Test 5 - we don't expect any transfer between random time series  but since you're only using 10 samples your results will be significantly biased upwards and have strong variance. Have a read of the section on statistical significance of our JIDT paper of the Transfer Entropy book. There's also no reason to expect a negative result here -- you only see negative results for local or pointwise values, or where the bias correction (in an estimator such as KSG) gives a result consistent with 0 (see more details in [this FAQ](https://github.com/jlizier/jidt/wiki/FAQs#what-does-it-mean-if-i-get-negative-results-from-a-kraskov-stoegbauer-grassberger-estimator))

**Closed by jlizier** 2018-11-19 10:23 UTC
