### ISSUE TITLE
Calling setObservations for ConditionalMutualInfoCalculatorMultiVariateWithDiscreteKraskov

### ISSUE THREAD

**Issue by pietromarchesi** [jlizier/jidt#70] opened 2018-06-19 10:41 UTC
While this works fine

```python
x = np.random.normal(size=[10000]).tolist()
y = np.random.choice(range(2), size=[10000]).tolist()

x = jpype.JArray(jpype.JDouble, 1)(x)
y = jpype.JArray(jpype.JInt, 1)(y)
MI_calc_class = jpype.JPackage("infodynamics.measures.mixed.kraskov").MutualInfoCalculatorMultiVariateWithDiscreteKraskov
MI_calc = MI_calc_class() 
MI_calc.initialise(1, 2)
MI_calc.setObservations(x, y)
MI_calc.computeAverageLocalOfObservations()
```

I can't figure out why the following fails:

```python
x = np.random.normal(size=[10000]).tolist()
y = np.random.choice(range(2), size=[10000]).tolist()
z = np.random.normal(size=[10000]).tolist()

x = jpype.JArray(jpype.JDouble, 1)(x)
y = jpype.JArray(jpype.JInt, 1)(y)
z = jpype.JArray(jpype.JDouble, 1)(z)

CMI_calc_class = jpype.JPackage("infodynamics.measures.mixed.kraskov").ConditionalMutualInfoCalculatorMultiVariateWithDiscreteKraskov

CMI_calc = CMI_calc_class()

CMI_calc.initialise(1, 2, 1)
CMI_calc.setObservations(x, y, z)
```

I only get the quite uninformative 
```python
RuntimeError: No matching overloads found for setObservations in find. at native/common/jp_method.cpp:127
```
From the docs I think that should be the correct calling pattern. I also tried the `startAddObservations`-`addObservations`-`finaliseAddObservations` route but it says it's not implemented.

**Comment by jlizier** [comment] 2018-06-19 12:43
No, not a bug -- this is not the correct calling pattern for the mixed CMI calculator and the error message about no matching overloads is correct. The definitive docs you should check here are the Javadocs, and these only define the ability to call setObservations with a univariate array for the MI version but not for CMI. For the CMI version in the current repo, you would need to convert the univariate arrays into multivariates as it stands.

With that said, I will add the required method in, as it will be good to have it included. Will push to the repo shortly ...

**Comment by pietromarchesi** [comment] 2018-06-19 13:12
I was looking in the Javadocs, the `setObservations`, which is defined in `ConditionalMutualInfoCalculatorMultiVariateWithDiscreteSourceCommon`, is defined as 

```
public void setObservations(double[][] continuousObservations,
                   int[] discreteObservations,
                   double[][] conditionedObservations)
```

Whereas for mutual information I was calling it as 

```
public void setObservations(double[][] continuousObservations,
                   int[] discreteObservations)
```

So I thought that just adding the conditioning variable, provided initialization was correct, would work. Where am I going wrong? And how would I make my arrays multivariates as you mentioned? Nothing I'm trying seems to work. 

(Also, sorry for posting this here as an issue,it would probably belong in the JIDT google group, which I just found).

**Comment by jlizier** [comment] 2018-06-19 13:31
Your MI python code actually calls:
```
public void setObservations(double[] continuousObservations,
                   int[] discreteObservations)
```
which exists additionally for the MI calculator but the corresponding method with univariate double arrays for the CMI did not exist until now. Never mind making multivariates work, the univariate code is there now. You will need to pull the latest from the repo and rebuild your jar.
I've tested your python code with the new methods implemented (jar rebuilt from the repo) and they work, so I am closing the issue.

(Yes, google group would be better when it's not clearly a bug)

**Closed by jlizier** 2018-06-19 13:31 UTC
Labels: enhancement
